package com.padeltmapp.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourtTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtTypeAllPropertiesEquals(CourtType expected, CourtType actual) {
        assertCourtTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCourtTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtTypeAllUpdatablePropertiesEquals(CourtType expected, CourtType actual) {
        assertCourtTypeUpdatableFieldsEquals(expected, actual);
        assertCourtTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtTypeAutoGeneratedPropertiesEquals(CourtType expected, CourtType actual) {
        assertThat(expected)
            .as("Verify CourtType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtTypeUpdatableFieldsEquals(CourtType expected, CourtType actual) {
        assertThat(expected)
            .as("Verify CourtType relevant properties")
            .satisfies(e -> assertThat(e.getCourtTypeName()).as("check courtTypeName").isEqualTo(actual.getCourtTypeName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtTypeUpdatableRelationshipsEquals(CourtType expected, CourtType actual) {
        assertThat(expected)
            .as("Verify CourtType relationships")
            .satisfies(e -> assertThat(e.getTournaments()).as("check tournaments").isEqualTo(actual.getTournaments()));
    }
}
